"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
format = "$directory $nix_shell$character "
right_format = "$git_status $git_branch $time"

[directory]
format = "$read_only[$path]($style)"
style = "red bold"
truncation_length = 2
truncate_to_repo = false

[character]
format = "[❯](bold #7480c2)"

[git_branch]
format = "[$symbol$branch]($style)"
style = "yellow"

[time]
format = "[$time](grey)"

[nix_shell]
format = "$symbol"
symbol = "❄️ "
