" https://GitHub.com/AlphaKeks/.dotfiles

set rtp+=~/.vim

set nocompatible
filetype plugin on
filetype indent on
syntax on

set autoindent
set autoread
set background=dark
set breakindent
set breakindentopt=shift:3
set colorcolumn=100
set complete=.
set completeopt=menu,menuone,preview,noinsert,noselect
set completeslash=slash
set concealcursor=nc
set conceallevel=2
set confirm
set copyindent
set cursorline
set display=lastline
set encoding=utf-8
set noexpandtab
set fileencoding=utf-8
set fillchars=stl:\ ,stlnc:\ ,fold:\ ,foldopen:,foldclose:,foldsep:\
set foldcolumn=0
set foldenable
set foldlevel=99
set foldmethod=indent
set formatoptions=crqn2lj
set grepformat=%f:%l:%c:%m
set grepprg=rg\ --vimgrep\ -i
set guicursor=a:block,r-cr-o-v:hor20
set history=999
set hlsearch
set icon
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:│\ ,trail:-
set matchtime=1
set menuitems=10
set more
set mouse=
set mousehide
set number
set path=.,**
set preserveindent
set pumheight=10
set pumwidth=15
set relativenumber
set ruler
set scrolloff=12
set shiftwidth=4
set shortmess=nxs
set showcmd
set showmatch
set signcolumn=yes
set smartcase
set smartindent
set splitbelow
set splitright
set noswapfile
set tabstop=4
set termguicolors
set textwidth=100
set title
set undodir=~/.vim/undo
set undofile
set updatetime=69
set wildchar=<C-n>
set wildmenu
set wildoptions=fuzzy,pum
set wrap

let g:netrw_banner=0
let g:netrw_liststyle=1
let g:netrw_bufsettings="nonu rnu noconfirm"

let g:mapleader=" "

nnoremap <Esc> :nohlsearch<CR>
nnoremap <Leader>e :Explore<CR>
nnoremap <C-s> :write<CR>
nnoremap U <C-r>
nnoremap x "_x

nnoremap Y y$
nnoremap <Leader>y "+y
vnoremap <Leader>y "+y
nnoremap <Leader>Y "+y$
vnoremap <Leader>Y "+y$

nnoremap <Leader>p "+p
vnoremap <Leader>p "+p
nnoremap <Leader>P "+P
vnoremap <Leader>P "+P

nnoremap J :silent! m +1<CR>==
nnoremap K :silent! m -2<CR>==
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

vnoremap < <gv
vnoremap > >gv

nnoremap <C-1> gt
nnoremap <C-2> 2gt
nnoremap <C-3> 3gt
nnoremap <C-4> 4gt
nnoremap <C-5> 5gt
nnoremap <C-6> 6gt
nnoremap <C-7> 7gt
nnoremap <C-8> 8gt
nnoremap <C-9> 9gt

nnoremap <C-Up> :resize +1<CR>
nnoremap <C-Down> :resize -1<CR>
nnoremap <C-Right> :vertical resize +1<CR>
nnoremap <C-Left> :vertical resize -1<CR>

tnoremap <C-Esc> <C-\><C-n>
nnoremap <Leader>t :tabedit \| terminal<CR>a

nnoremap <Leader>qo :copen<CR>
nnoremap <Leader>qn :cnext<CR>
nnoremap <Leader>qp :cprev<CR>

nnoremap <Leader>ff :find *
nnoremap <Leader>fl :grep 
nnoremap <C-/> :g/<C-r><C-w>/#<CR>:

colorscheme catppuccin

" vim: et ts=2 sw=2 sts=2 ai si ft=vim
