#!/usr/bin/env zsh

# https://GitHub.com/AlphaKeks/.dotfiles

# Only run in interactive mode.
[[ $- != *i* ]] && return

# History settings
HISTFILE=$ZHIST
HISTSIZE=100000
SAVEHIST=100000

# vim bindings
bindkey -v

# How is this not default?
bindkey "^H" backward-kill-word
bindkey "^r" history-incremental-search-backward
KEYTIMEOUT=1

# Prompt
eval "$(starship init zsh)"

# Load plugins
source $ZDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Load aliases
source $DOTFILES/configs/env/aliases

# Nix
eval "$(direnv hook zsh)"

